---
defaults:
  active: true
  occurrences: 12
  role: dm
games:
  Insanity:
    frequency: 1st Saturday
  Matsif:
    frequency: 3rd Saturday
    role: player
  Gwynzer:
    frequency: 4th Saturday
    role: player
  Noah:
    frequency: Every 2 weeks
    starting: '2020-11-07'
  Kaela:
    active: false
    frequency: Every 3 weeks
    starting: '2020-09-06'
