
module DndSchedule

  # A Game has multiple Sessions generated by its Schedule.
  # A Game has a Schedule from which many Sessions are generated.
  class Game

    attr_reader :name, :role

    def initialize options
      self.name = options.delete('name')
      self.role = options.delete('role')
      set_schedule! options
    end

    def sessions
      schedule.sessions.collect do |session|
        session.name = name
        session.role = role
        session
      end
    end

    private

    attr_accessor :schedule
    attr_writer :name, :role

    private

    def set_schedule! options
      if options['frequency'].nil?
        raise DndSchedule::Error, "Game '#{name}' is missing its 'frequency' configuration. Please correct and try again."
      else
        self.schedule = DndSchedule::Schedule.new options
      end
    end

  end
end
